apiVersion : apps/v1
kind: Deployment
metadata:
  name: appcustomnginxaks 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appcustomnginxaks
  template:
    metadata:
      labels:
        app: appcustomnginxaks 
    spec:
      containers:
        - name: appcustomnginxaks 
          image: shanukumarm.azurecr.io/app/customnginx:26
          ports:
          - containerPort: 80